services:
  # image project
  app:
    container_name: app-container
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # nginx
  nginx:
    container_name: nginx-container
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # mysqla
  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # node
  node:
    container_name: node-container
    image: node:23
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: [ "sh", "-c", "while :; do sleep 1; done" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
